### ISSUE TITLE
 System time is way off (before 2016-01-01)

### ISSUE THREAD

**Issue by Jordyleef** [garbear/kodi-steamlink#28]
I installed the latest version of Kodi 17.6, installation went well. but then after installing the YouTube add-on a could not sign in or use it. So I checked the logs and found a time and date error.

01:09:48.136 T:2602562512   ERROR: /home/apps/kodi/.home/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py:306: SystemTimeWarning: System time is way off (before 2016-01-01). This will probably lead to SSL verification errors. My time region is set correct and as far as i know is the network working.

Full log: ``01:06:43.262 T:2676683728   DEBUG: Previous line repeats 125 times.
01:06:43.262 T:2676683728   DEBUG: Failed to connect to LIRC. Giving up.
01:06:43.262 T:2676683728   DEBUG: Thread RemoteControl 2676683728 terminating
01:06:43.375 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:06:56.119 T:3000550352   DEBUG: Previous line repeats 17 times.
01:06:56.119 T:3000550352   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
01:06:56.120 T:3000550352   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated
01:06:56.122 T:3000557568   DEBUG: ------ Window Init () ------
01:06:56.122 T:3000557568   DEBUG: Alloc resources: 0.01ms  (0.01 ms skin load)
01:06:57.207 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:16.826 T:3000550352   DEBUG: Previous line repeats 181 times.
01:09:16.826 T:3000550352   DEBUG: CAnnouncementManager - Announcement: OnScreensaverDeactivated from xbmc
01:09:16.826 T:3000550352   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverDeactivated
01:09:16.826 T:3000557568   DEBUG: OnKey: 168 (0xa8, obc87) pressed, screen saver/dpms woken up
01:09:16.995 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:17.848 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:17.848 T:3000557568   DEBUG: ------ Window Deinit () ------
01:09:18.530 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:19.159 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:19.160 T:3000557568   DEBUG: OnKey: 169 (0xa9, obc86) pressed, action is Left
01:09:19.160 T:2961896400    INFO: CActiveAESink::OpenSink - initialize sink
01:09:19.160 T:2961896400   DEBUG: CActiveAESink::OpenSink - trying to open device STEAMLINK:SteamLink
01:09:19.241 T:2961896400   DEBUG: CActiveAESink::OpenSink - SteamLinkAudio Initialized:
01:09:19.241 T:2961896400   DEBUG:   Output Device : Steam Link Low Latency Audio
01:09:19.242 T:2961896400   DEBUG:   Sample Rate   : 48000
01:09:19.242 T:2961896400   DEBUG:   Sample Format : AE_FMT_S16NE
01:09:19.242 T:2961896400   DEBUG:   Channel Count : 2
01:09:19.242 T:2961896400   DEBUG:   Channel Layout: FL,FR
01:09:19.242 T:2961896400   DEBUG:   Frames        : 2400
01:09:19.242 T:2961896400   DEBUG:   Frame Size    : 4
01:09:19.250 T:2978673616   DEBUG: Thread SteamLinkAudio start, auto delete: false
01:09:20.065 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:20.282 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:20.282 T:3000557568   DEBUG: OnKey: menu (0xd8) pressed, action is PreviousMenu
01:09:20.300 T:3000557568   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
01:09:20.598 T:3000557568   DEBUG: ------ Window Deinit (SettingsCategory.xml) ------
01:09:20.604 T:3000557568   DEBUG: CGUIWindowManager::PreviousWindow: Activate new
01:09:20.604 T:3000557568   DEBUG: ------ Window Init (Settings.xml) ------
01:09:20.608 T:3000557568   DEBUG: Window Settings.xml was already loaded
01:09:20.609 T:3000557568   DEBUG: Alloc resources: 3.85ms
01:09:21.601 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:23.041 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:23.041 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:23.136 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:24.087 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:24.087 T:3000557568   DEBUG: OnKey: menu (0xd8) pressed, action is PreviousMenu
01:09:24.088 T:3000557568   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
01:09:24.423 T:3000557568   DEBUG: ------ Window Deinit (Settings.xml) ------
01:09:24.444 T:3000557568   DEBUG: CGUIWindowManager::PreviousWindow: Activate new
01:09:24.444 T:3000557568   DEBUG: ------ Window Init (Home.xml) ------
01:09:24.450 T:3000557568   DEBUG: Window Home.xml was already loaded
01:09:24.451 T:3000557568   DEBUG: Alloc resources: 6.45ms
01:09:24.670 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:25.667 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:25.667 T:3000557568   DEBUG: OnKey: 169 (0xa9, obc86) pressed, action is Left
01:09:26.175 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:26.188 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:26.457 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:26.458 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:27.741 T:2442875856   DEBUG: Previous line repeats 4 times.
01:09:27.742 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:28.069 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:28.070 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:28.106 T:2693460944   DEBUG: Thread JobWorker start, auto delete: true
01:09:29.276 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:32.929 T:3000557568   DEBUG: Previous line repeats 5 times.
01:09:32.932 T:3000557568   DEBUG: OnKey: 168 (0xa8, obc87) pressed, action is Right
01:09:33.881 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:34.097 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:34.097 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:34.288 T:2693460944   DEBUG: DoWork - took 188 ms to load special://masterprofile/Thumbnails/7/76e3a364.jpg
01:09:34.467 T:3000557568   DEBUG: OnKey: 11 (0x0b, obc244) pressed, action is Select
01:09:34.470 T:3000557568   DEBUG: Activating window ID: 10025
01:09:34.814 T:3000557568   DEBUG: ------ Window Deinit (Home.xml) ------
01:09:34.864 T:3000557568   DEBUG: ------ Window Init (MyVideoNav.xml) ------
01:09:34.864 T:3000557568    INFO: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
01:09:35.290 T:3000557568   DEBUG: Load MyVideoNav.xml: 416.33ms
01:09:35.291 T:3000557568   DEBUG: CDirectoryProvider[]: refreshing..
01:09:35.291 T:2693460944   ERROR: GetDirectory - Error getting
01:09:35.291 T:3000557568   DEBUG: CDirectoryProvider[]: refreshing..
01:09:35.292 T:2693460944   ERROR: GetDirectory - Error getting
01:09:35.292 T:3000557568   DEBUG: CDirectoryProvider[]: refreshing..
01:09:35.292 T:2693460944   ERROR: GetDirectory - Error getting
01:09:35.292 T:3000557568   DEBUG: CDirectoryProvider[]: refreshing..
01:09:35.293 T:2693460944   ERROR: GetDirectory - Error getting
01:09:35.293 T:3000557568   DEBUG: CDirectoryProvider[]: refreshing..
01:09:35.294 T:2693460944   ERROR: GetDirectory - Error getting
01:09:35.294 T:3000557568   DEBUG: CDirectoryProvider[]: refreshing..
01:09:35.294 T:2693460944   ERROR: GetDirectory - Error getting
01:09:35.294 T:3000557568   DEBUG: CDirectoryProvider[]: refreshing..
01:09:35.294 T:2693460944   ERROR: GetDirectory - Error getting
01:09:35.297 T:3000557568   DEBUG: Alloc resources: 432.36ms  (426.13 ms skin load)
01:09:35.398 T:3000557568   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.youtube/)
01:09:35.398 T:3000557568   DEBUG:   ParentPath = [plugin://plugin.video.youtube/]
01:09:35.407 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:35.430 T:2434487248   DEBUG: Thread JobWorker start, auto delete: true
01:09:35.441 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:35.461 T:2693460944   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.youtube] took 63 ms
01:09:35.462 T:2434487248   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/','1','')
01:09:35.463 T:2685072336   DEBUG: Thread JobWorker start, auto delete: true
01:09:35.463 T:2602562512   DEBUG: Thread LanguageInvoker start, auto delete: false
01:09:35.463 T:2602562512    INFO: initializing python engine.
01:09:35.463 T:2602562512   DEBUG: CPythonInvoker(2, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
01:09:35.559 T:2602562512   DEBUG: -->Python Interpreter Initialized<--
01:09:35.559 T:2602562512   DEBUG: CPythonInvoker(2, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py"
01:09:35.561 T:2602562512   DEBUG: CPythonInvoker(2, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): setting the Python path to /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib:/home/apps/kodi/.home/.kodi/addons/script.module.certifi/lib:/home/apps/kodi/.home/.kodi/addons/script.module.chardet/lib:/home/apps/kodi/.home/.kodi/addons/script.module.idna/lib:/home/apps/kodi/.home/.kodi/addons/script.module.requests/lib:/home/apps/kodi/.home/.kodi/addons/script.module.six/lib:/home/apps/kodi/.home/.kodi/addons/script.module.urllib3/lib:/home/apps/kodi/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/home/apps/kodi/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-linux-x86_64.egg:/home/apps/kodi/lib/python27.zip:/home/apps/kodi/lib/python2.7:/home/apps/kodi/lib/python2.7/plat-linux2:/home/apps/kodi/lib/python2.7/lib-tk:/home/apps/kodi/lib/python2.7/lib-old:/home/apps/kodi/lib/python2.7/lib-dynload:/home/apps/kodi/lib/python2.7/site-packages
01:09:35.561 T:2602562512   DEBUG: CPythonInvoker(2, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib
01:09:35.561 T:2602562512   DEBUG: CPythonInvoker(2, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.20.0 of the xbmc.python api
01:09:35.918 T:3000557568   DEBUG: ------ Window Init (DialogBusy.xml) ------
01:09:35.919 T:3000557568   DEBUG: Window DialogBusy.xml was already loaded
01:09:35.919 T:3000557568   DEBUG: Alloc resources: 0.06ms
01:09:37.056 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:38.360 T:2602562512   DEBUG: Previous line repeats 1 times.
01:09:38.360 T:2602562512   DEBUG: [plugin.video.youtube] send_notification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": false, "whitelist": "", "httpd_port": 50152}|
01:09:38.368 T:2602562512   DEBUG: [plugin.video.youtube] JSONStore Load |/home/apps/kodi/.home/.kodi/userdata/addon_data/plugin.video.youtube/api_keys.json|
01:09:38.374 T:2602562512   DEBUG: [plugin.video.youtube] JSONStore Load |/home/apps/kodi/.home/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
01:09:38.397 T:3000550352   DEBUG: CAnnouncementManager - Announcement: check_settings from plugin.video.youtube
01:09:38.397 T:3000550352   DEBUG: GOT ANNOUNCEMENT, type: 512, from plugin.video.youtube, message check_settings
01:09:38.504 T:2602562512   DEBUG: [plugin.video.youtube] User: |0| Using API key set: |1|
01:09:38.602 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:38.832 T:2621264848   DEBUG: Previous line repeats 1 times.
01:09:38.832 T:2621264848   DEBUG: [plugin.video.youtube] onNotification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": false, "whitelist": "", "httpd_port": 50152}|
01:09:38.840 T:2602562512   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
01:09:39.023 T:2602562512  NOTICE: [plugin.video.youtube] Running: YouTube (6.1.3) on Krypton (Kodi-17.6) with Python 2.7.12
                                                Path: /
                                                Params: {}
01:09:39.209 T:2602562512   DEBUG: [plugin.video.youtube] JSONStore Load |/home/apps/kodi/.home/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
01:09:39.223 T:2602562512   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
01:09:39.235 T:2602562512   DEBUG: [plugin.video.youtube] User is not logged in
01:09:39.235 T:2602562512   DEBUG: [plugin.video.youtube] Setting content-type: "files" for "/"
01:09:39.298 T:2602562512   DEBUG: [plugin.video.youtube] Shutdown of Kodion
01:09:39.298 T:2602562512    INFO: CPythonInvoker(2, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
01:09:39.333 T:3000557568   DEBUG: Saving fileitems [plugin://plugin.video.youtube/]
01:09:39.335 T:3000557568   DEBUG:   -- items: 8, sort method: 0, ascending: false
01:09:39.358 T:2527065040   DEBUG: Thread BackgroundLoader start, auto delete: false
01:09:39.503 T:2527065040   DEBUG: Thread BackgroundLoader 2527065040 terminating
01:09:39.642 T:3000557568   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
01:09:39.762 T:2602562512    INFO: Python script stopped
01:09:39.768 T:2602562512   DEBUG: Thread LanguageInvoker 2602562512 terminating
01:09:40.126 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:41.579 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:41.579 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:41.660 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:41.764 T:2693460944   DEBUG: Previous line repeats 1 times.
01:09:41.764 T:2693460944   DEBUG: DoWork - took 182 ms to load special://masterprofile/Thumbnails/d/ddce672a.jpg
01:09:42.215 T:3000557568   DEBUG: OnKey: 11 (0x0b, obc244) pressed, action is Select
01:09:42.219 T:3000557568   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.youtube/sign/in/)
01:09:42.219 T:3000557568   DEBUG:   ParentPath = [plugin://plugin.video.youtube/]
01:09:42.276 T:2434487248   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.youtube] took 57 ms
01:09:42.277 T:2685072336   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/sign/in/','2','')
01:09:42.278 T:2602562512   DEBUG: Thread LanguageInvoker start, auto delete: false
01:09:42.278 T:2602562512    INFO: initializing python engine.
01:09:42.278 T:2602562512   DEBUG: CPythonInvoker(3, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
01:09:42.375 T:2602562512   DEBUG: -->Python Interpreter Initialized<--
01:09:42.376 T:2602562512   DEBUG: CPythonInvoker(3, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py"
01:09:42.378 T:2602562512   DEBUG: CPythonInvoker(3, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): setting the Python path to /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib:/home/apps/kodi/.home/.kodi/addons/script.module.certifi/lib:/home/apps/kodi/.home/.kodi/addons/script.module.chardet/lib:/home/apps/kodi/.home/.kodi/addons/script.module.idna/lib:/home/apps/kodi/.home/.kodi/addons/script.module.requests/lib:/home/apps/kodi/.home/.kodi/addons/script.module.six/lib:/home/apps/kodi/.home/.kodi/addons/script.module.urllib3/lib:/home/apps/kodi/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/home/apps/kodi/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-linux-x86_64.egg:/home/apps/kodi/lib/python27.zip:/home/apps/kodi/lib/python2.7:/home/apps/kodi/lib/python2.7/plat-linux2:/home/apps/kodi/lib/python2.7/lib-tk:/home/apps/kodi/lib/python2.7/lib-old:/home/apps/kodi/lib/python2.7/lib-dynload:/home/apps/kodi/lib/python2.7/site-packages
01:09:42.378 T:2602562512   DEBUG: CPythonInvoker(3, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib
01:09:42.378 T:2602562512   DEBUG: CPythonInvoker(3, /home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.20.0 of the xbmc.python api
01:09:42.755 T:3000557568   DEBUG: ------ Window Init (DialogBusy.xml) ------
01:09:42.756 T:3000557568   DEBUG: Window DialogBusy.xml was already loaded
01:09:42.756 T:3000557568   DEBUG: Alloc resources: 0.21ms
01:09:43.195 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:45.372 T:2602562512   DEBUG: Previous line repeats 3 times.
01:09:45.372 T:2602562512   DEBUG: [plugin.video.youtube] send_notification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": false, "whitelist": "", "httpd_port": 50152}|
01:09:45.376 T:2602562512   DEBUG: [plugin.video.youtube] JSONStore Load |/home/apps/kodi/.home/.kodi/userdata/addon_data/plugin.video.youtube/api_keys.json|
01:09:45.382 T:2602562512   DEBUG: [plugin.video.youtube] JSONStore Load |/home/apps/kodi/.home/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
01:09:45.386 T:3000550352   DEBUG: CAnnouncementManager - Announcement: check_settings from plugin.video.youtube
01:09:45.386 T:3000550352   DEBUG: GOT ANNOUNCEMENT, type: 512, from plugin.video.youtube, message check_settings
01:09:45.412 T:2621264848   DEBUG: [plugin.video.youtube] onNotification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": false, "whitelist": "", "httpd_port": 50152}|
01:09:45.518 T:2602562512   DEBUG: [plugin.video.youtube] User: |0| Using API key set: |1|
01:09:45.840 T:2602562512   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
01:09:46.022 T:2602562512  NOTICE: [plugin.video.youtube] Running: YouTube (6.1.3) on Krypton (Kodi-17.6) with Python 2.7.12
                                                Path: /sign/in/
                                                Params: {}
01:09:46.071 T:2602562512   DEBUG: [plugin.video.youtube] JSONStore Load |/home/apps/kodi/.home/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
01:09:46.134 T:3000557568   DEBUG: ------ Window Init (DialogConfirm.xml) ------
01:09:46.134 T:3000557568    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
01:09:46.143 T:3000557568   DEBUG: Load DialogConfirm.xml: 9.00ms
01:09:46.146 T:3000557568   DEBUG: Alloc resources: 11.85ms  (9.26 ms skin load)
01:09:46.266 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:47.626 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:47.728 T:3000557568   DEBUG: OnKey: 11 (0x0b, obc244) pressed, action is Select
01:09:47.801 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:47.914 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:47.914 T:3000557568   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
01:09:47.948 T:2602562512   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
01:09:47.967 T:2602562512   DEBUG: [plugin.video.youtube] User is not logged in
01:09:47.972 T:2602562512   DEBUG: [plugin.video.youtube] Requesting device and user code: Config: |YouTube-TV| Client id [:5]: |86155|
01:09:48.136 T:2602562512   ERROR: /home/apps/kodi/.home/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py:306: SystemTimeWarning: System time is way off (before 2016-01-01). This will probably lead to SSL verification errors
                                              SystemTimeWarning
01:09:48.468 T:2602562512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/device/code (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
                                            Traceback (most recent call last):
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 43, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 87, in navigate
                                                result = method(context, re_match)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 11, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 886, in _on_sign
                                                yt_login.process(mode, self, context, re_match)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_login.py", line 113, in process
                                                access_token_tv, expires_in_tv, refresh_token_tv = _do_login(_for_tv=True)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_login.py", line 44, in _do_login
                                                json_data = _client.request_device_and_user_code_tv()
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/login_client.py", line 204, in request_device_and_user_code_tv
                                                return self.request_device_and_user_code(client_id=client_id)
                                              File "/home/apps/kodi/.home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/login_client.py", line 224, in request_device_and_user_code
                                                result = requests.post(url, data=post_data, headers=headers, verify=self._verify)
                                              File "/home/apps/kodi/.home/.kodi/addons/script.module.requests/lib/requests/api.py", line 112, in post
                                                return request('post', url, data=data, json=json, **kwargs)
                                              File "/home/apps/kodi/.home/.kodi/addons/script.module.requests/lib/requests/api.py", line 58, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/apps/kodi/.home/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 512, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/apps/kodi/.home/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 622, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/apps/kodi/.home/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 511, in send
                                                raise SSLError(e, request=request)
                                            SSLError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/device/code (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
                                            -->End of Python script error report<--
01:09:48.480 T:3000557568   DEBUG: ------ Window Init (DialogNotification.xml) ------
01:09:48.480 T:3000557568   DEBUG: Window DialogNotification.xml was already loaded
01:09:48.480 T:3000557568   DEBUG: Alloc resources: 0.01ms
01:09:49.000 T:2602562512    INFO: Python script stopped
01:09:49.008 T:2602562512   DEBUG: Thread LanguageInvoker 2602562512 terminating
01:09:49.048 T:3000557568   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/sign/in/
01:09:49.056 T:3000557568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/sign/in/) failed
01:09:49.056 T:3000557568   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.youtube/)
01:09:49.057 T:3000557568   DEBUG:   ParentPath = [plugin://plugin.video.youtube/]
01:09:49.080 T:3000557568   DEBUG: Loading items: 8, directory: plugin://plugin.video.youtube/ sort method: 0, ascending: false
01:09:49.107 T:2693460944   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.youtube] took 50 ms
01:09:49.120 T:2602562512   DEBUG: Thread BackgroundLoader start, auto delete: false
01:09:49.221 T:2602562512   DEBUG: Thread BackgroundLoader 2602562512 terminating
01:09:49.331 T:3000557568   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
01:09:49.336 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:49.888 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:49.888 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:50.871 T:2442875856   DEBUG: Previous line repeats 4 times.
01:09:50.871 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:51.305 T:3000557568   DEBUG: Previous line repeats 1 times.
01:09:51.305 T:3000557568   DEBUG: OnKey: 167 (0xa7, obc88) pressed, action is Down
01:09:52.407 T:2442875856   DEBUG: Previous line repeats 1 times.
01:09:52.407 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
01:09:54.335 T:3000557568   DEBUG: Previous line repeats 3 times.
01:09:54.335 T:3000557568   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
01:09:55.476 T:2442875856   DEBUG: CWebServer[8080]: request received for /jsonrpc
``

**Comment by garbear** [comment]
Kodi doesn't include NTP services that sync with the network. This functionality is delegated to the OS. I'm not sure how the steam link handles NTP, but I can look into this before the v18 release.

**Comment by jwhengeveld** [comment]
Is there a possibility to manually set the time and date? Mine stays at 2008

**Comment by Sonic198** [comment]
Any update on that?

Actually I found that steam link should automatically update date & time according to this link
https://steamcommunity.com/app/353380/discussions/0/276237094327701818/

So maybe Kodi can't get access to that?

**Comment by Jordyleef** [comment]
I fixed the problem with this:

I used SSH to access the device and then:
summary:
I used the preinstalled busybox ntp daemon to sync the time with the ntp server. I did this by creating a config file called ntp.conf in '/etc' folder. In the config file I wrote the following line:

server pool.ntp.org

This is a pool of ntp servers which you will connect to in order to sync your time. At last, I added a shell script to the /etc/init.d/startup folder to make sure the ntp daemon is started during startup. The shell script looks like this:

#!/bin/sh
sleep 10
ntpd &

And I called the script 'S98ntpinit' (without the extension .sh not sure if this is needed or not).
The sleep 10 is there to make sure the dhcp client is started before ntpd is started. Otherwise, the ntp daemon will throw an error saying pool.ntp.org does not exist.

Hope this can help someone.

**Comment by Sonic198** [comment]
I fixed that by factory reset of my steam link and install updates again.

**Comment by Revadike** [comment]
@Jordyleef your `ntpd` method really works
![image](https://user-images.githubusercontent.com/4411977/50597491-dd802180-0ea7-11e9-8421-8b0de1a05f0b.png)
Except the startup script doesn't unfortunately :(
I tried with and without .sh extension, but the steam link doesn't execute it at startup.
Do you know any other ways?

Edit:
Managed to fix it by running:
`chmod +x /etc/init.d/S98ntpinit`

**Comment by slax57** [comment]
This problem is Steamlink related (not Kodi) and is well described here: https://steamcommunity.com/app/353380/discussions/0/1710690176751438010/

Actually there is no need to set up SSH to fix this issue, you can simply set up the NTP Pool of your choice in Steamlink Settings -> Network -> Advanced Settings -> Timeserver

:-)
